### ISSUE TITLE
Full URL 

### ISSUE THREAD

**Issue by juergensalesski** [jonathanheilmann/ext-jh_opengraphprotocol#61] opened 2018-04-27 10:57 UTC
https://github.com/jonathanheilmann/ext-jh_opengraphprotocol/blob/7344f95decc9475cdfa71c2ac70fbb65b247da05/Classes/Service/OgRendererService.php#L150

you need this:

` $lConf = [
            'additionalParams' => '&' . GeneralUtility::implodeArrayForUrl('', $additionalParams),
            'parameter' => $GLOBALS['TSFE']->id,
            'forceAbsoluteUrl' => true
        ];`

aslo: **  'forceAbsoluteUrl' => true**

**Comment by jonathanheilmann** [comment] 2018-04-27 19:46
Duplicate of #59

**Closed by jonathanheilmann** 2018-04-27 19:46 UTC
